"""empty message

Revision ID: 090d6203bd33
Revises: 3165ef08c5ac
Create Date: 2021-05-18 00:13:47.573375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090d6203bd33'
down_revision = '3165ef08c5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_talent')
    # ### end Alembic commands ###
