"""empty message

Revision ID: 3165ef08c5ac
Revises: 
Create Date: 2021-05-18 00:13:07.474623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3165ef08c5ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
